"1-2-3-5":
  name: "1-2-3-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 2
  invertible: True

"1-2-b3-5":
  name: "1-2-b3-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 2
  invertible: True

"1-2-4-5":
  name: "1-2-4-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 2
  invertible: True

"1-3-4-5":
  name: "1-3-4-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 2
  invertible: True

"1-b3-4-5":
  name: "1-b3-4-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 2
  invertible: True

"b3-1-2-4-5":
  name: "b3-1-2-4-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 5
  notes_per_beat: 5
  max_interval: 2
  invertible: False

"b7-8-6-b7-5-b3-2-1":
  name: "b7-8-6-b7-5-b3-2-1"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 2
  invertible: False

"5-b3-4-b7-5-b3-1":
  name: "5-b3-4-b7-5-b3-1"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 7
  notes_per_beat: 7
  max_interval: 2
  invertible: False

"1-2-5":
  name: "1-2-5"
  category: patterns
  keyed_or_chromatic: chromatic
  number_of_notes: 7
  notes_per_beat: 7
  max_interval: 2
  invertible: True
