####################### Basic Arpeggios ##########################

"Major Triads: 1-3-5":
  name: "Major Triads: 1-3-5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Minor Triads: 1-b3-5":
  name: "Minor Triads: 1-b3-5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Diminished Triads: 1-b3-b5":
  name: "Diminished Triads: 1-b3-b5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Augmented Triads: 1-3-#5":
  name: "Augmented Triads: 1-3-#5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Suspended Triads: 1-4-5":
  name: "Suspended Triads: 1-4-5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Major 5b Triads: 1-3-b5":
  name: "Major b5 Triads: 1-3-b5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 3
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

######## 7ths Chords #########


"Major 7ths":
  name: "Major 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Major 7ths b5":
  name: "Major 7ths b5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Augmented Major 7ths":
  name: "Augmented Major 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

## 7th
"7ths":
  name: "7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"7ths b5":
  name: "7ths b5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"7ths #5":
  name: "7ths #5"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Minor
"Minor 7ths":
  name: "Minor 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Minor Major 7ths":
  name: "Minor Major 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Diminished
"Diminished 7ths":
  name: "Diminished 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Diminished Major 7ths":
  name: "Diminished 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Suspended
"Suspended 7ths":
  name: "Suspended 7ths"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 4
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True


########################## Dann-esque arpeggios ###################

"Major 6-Note: 1-3-5-3-1-3":
  name: "Major 6-Note: 1-3-5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Minor 6-Note: 1-b3-5-b3-1-b3":
  name: "Minor 6-Note: 1-b3-5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Diminished 6-Note: 1-b3-b5-b3-1-b3":
  name: "Diminished 6-Note: 1-b3-b5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True


"Augmented 6-Note: 1-3-#5-3-1-3":
  name: "Augmented 6-Note: 1-3-#5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Suspended 6-Note: 1-4-5-4-1-4":
  name: "Suspended 6-Note: 1-4-5-4-1-4"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

"Major 5b 6-Note: 1-3-b5-3-1-3":
  name: "Major 5b 6-Note: 1-3-b5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2]
  invertible: True

## 7th chords:

## Major
"Major 7ths 8-Note: 1-3-5-7-5-3-1-3":
  name: "Major 7ths 8-Note: 1-3-5-7-5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Major 7ths b5 8-Note: 1-3-b5-7-b5-3-1-3":
  name: "Major 7ths b5 8-Note: 1-3-b5-7-b5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Augmented Major 7ths 8-Note: 1-3-#5-7-#5-3-1-3":
  name: "Augmented Major 7ths 8-Note: 1-3-#5-7-#5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

## 7th
"7ths 8-Note: 1-3-5-b7-5-3-1-3":
  name: "7ths 8-Note: 1-3-5-b7-5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"7ths b5 8-Note: 1-3-b5-b7-b5-3-1-3":
  name: "7ths b5 8-Note: 1-3-b5-b7-b5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"7ths #5 8-Note: 1-3-#5-b7-#5-3-1-3":
  name: "7ths #5 8-Note: 1-3-#5-b7-#5-3-1-3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Minor
"Minor 7ths 8-Note: 1-b3-5-b7-5-b3-1-b3":
  name: "Minor 7ths 8-Note: 1-b3-5-b7-5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Minor Major 7ths 8-Note: 1-b3-5-7-5-b3-1-b3":
  name: "Minor Major 7ths 8-Note: 1-b3-5-7-5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Diminished
"Diminished 7ths 8-Note: 1-b3-b5-bb7-b5-b3-1-b3":
  name: "Diminished 7ths 8-Note: 1-b3-b5-bb7-b5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

"Diminished Major 7ths 8-Note: 1-b3-b5-7-b5-b3-1-b3":
  name: "Diminished 7ths 8-Note: 1-b3-b5-7-b5-b3-1-b3"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True

# Suspended
"Suspended 7ths 8-Note: 1-4-5-b7-5-4-1-4":
  name: "Suspended 7ths 8-Note: 1-4-5-b7-5-4-1-4"
  category: arpeggios
  keyed_or_chromatic: chromatic
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  inversions: [0, 1, 2, 3]
  invertible: True


######################## Combo Interval Arpeggios ############################