"Major":
  name: "Major"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, Db, D, Eb, E, F, Gb, G]
  scale: diatonic
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 4, 5, 7, 9, 11]

"Melodic Minor":
  name: "Melodic Minor"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: melodic minor
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 3, 5, 7, 9, 11]

"Harmonic Minor":
  name: "Harmonic Minor"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: harmonic minor
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 3, 5, 7, 8, 11]


"Diminished":
  name: "Diminished"
  category: scales
  keyed_or_chromatic: keyed
  key: [Bb, B, C]
  scale: diminished
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 3, 5, 6, 8, 9, 11]

"Whole-Tone":
  name: "Whole-Tone"
  category: scales
  keyed_or_chromatic: keyed
  key: [Bb, B]
  scale: whole tone
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 4, 6, 8, 10]

"Pentatonic":
  name: "Pentatonic"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: Pentatonic
  number_of_notes: 5
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 2, 4, 7, 9]

"Japanese":
  name: "Japanese"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: japanese
  number_of_notes: 5
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 1, 5, 7, 8]

"Pentatonic b3":
  name: "Pentatonic b3"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: japanese
  number_of_notes: 5
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 1, 5, 7, 10]

"Blues Scale":
  name: "Blues Scale"
  category: scales
  keyed_or_chromatic: keyed
  key: [Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G]
  scale: blues
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  invertible: False
  scale_notes: [0, 3, 5, 6, 7, 10]



# Do diminished, whole tone, other scale types, etc.

# Ask josh about learning wiht respect to these augmentations