"Major":
  name: "Major"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, Db, D, Eb, E, F, Gb, G
  scale: diatonic
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 4, 5, 7, 9, 11

"Melodic Minor":
  name: "Melodic Minor"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G
  scale: melodic minor
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 3, 5, 7, 9, 11

"Harmonic Minor":
  name: "Harmonic Minor"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G
  scale: harmonic minor
  number_of_notes: 7
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 3, 5, 7, 8, 11


"Diminished":
  name: "Diminished"
  keyed_or_chromatic: keyed
  key: Bb, B, C
  scale: diminished
  number_of_notes: 8
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 3, 5, 6, 8, 9, 11

"Whole-Tone":
  name: "Whole-Tone"
  keyed_or_chromatic: keyed
  key: Bb, B
  scale: whole tone
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 4, 6, 8, 10

"Pentatonic":
  name: "Pentatonic"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G
  scale: Pentatonic
  number_of_notes: 5
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 2, 4, 7, 9

"Japanese":
  name: "Japanese"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G
  scale: japanese
  number_of_notes: 5
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 1, 5, 7, 8

"Blues Scale":
  name: "Blues Scale"
  keyed_or_chromatic: keyed
  key: Ab, A, Bb, B, C, C#, D, Eb, E, F, F#, G
  scale: blues
  number_of_notes: 6
  notes_per_beat: 4
  max_interval: 1
  invertable: False
  scale_notes: 0, 3, 5, 6, 7, 10



# Do diminished, whole tone, other scale types, etc.

# Ask josh about learning wiht respect to these augmentations